{{- $fullName := include "alertmanager-webhook-telegram.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-token
  labels:
    app: {{ include "alertmanager-webhook-telegram.name" . }}
    chart: {{ include "alertmanager-webhook-telegram.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  BOT_TOKEN: "{{ required "A Telegram Bot Token is required!" .Values.config.telegram.bot_token | b64enc }}"
  {{- if not (empty .Values.config.basic_auth.enabled) }}
  BASIC_AUTH_PASSWORD: "{{ required "You must specify Basic Auth password if Basic Auth is enabled." $.Values.config.basic_auth.password | b64enc }}"
  BASIC_AUTH_USERNAME: "{{ required "You must specify Basic Auth usernname if Basic Auth is enabled." $.Values.config.basic_auth.username | b64enc }}"
  {{- end }}
  