{{- $fullName := include "alertmanager-webhook-telegram.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-token
  labels:
    app: {{ include "alertmanager-webhook-telegram.name" . }}
    chart: {{ include "alertmanager-webhook-telegram.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not (empty .Values.config.telegram.bot_token) }}
  BOT_TOKEN: "{{ .Values.config.telegram.bot_token | b64enc }}"
  {{ else }}
  BOT_TOKEN: {{ required "A Telegram Bot Token is required!" .Values.config.telegram.bot_token }}
  {{- end }}